words = [
    {w:"complement", t:"v,n", link:"https://dictionary.cambridge.org/dictionary/english/complement"},
    {w:"compile", t:"v,n", link:"https://dictionary.cambridge.org/dictionary/english/compile"},
    {w:"competent", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english-arabic/competent"},
    {w:"competence", t:"n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/competence"},
    {w:"compensation", t:"n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/compensation"},
    {w:"compelling", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english/compelling"},
    {w:"comparative", t:"adj,n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/comparative"},
    {w:"comparable", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english/comparative"},
    {w:"companion", t:"n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/companion"},
    {w:"compact", t:"adj,v", link:"https://dictionary.cambridge.org/dictionary/english/compact"},

    {w:"commute", t:"v,n", link:"https://dictionary.cambridge.org/dictionary/english/commute"},
    {w:"common", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english-arabic/common"},
    {w:"committee", t:"n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/committee"},
    {w:"commitment", t:"n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/commitment"},
    {w:"commencement", t:"n", link:"https://dictionary.cambridge.org/dictionary/english/commencement"},
    {w:"commemorate", t:"v", link:"https://dictionary.cambridge.org/dictionary/english/commemorate"},
    {w:"colonists", t:"n", link:"https://dictionary.cambridge.org/dictionary/english/colonist?q=colonists"},
    {w:"collaboration", t:"n", link:"https://dictionary.cambridge.org/dictionary/english/collaboration"},
    {w:"coherent", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english/coherent"},
    {w:"coffin", t:"n,v", link:"https://dictionary.cambridge.org/dictionary/english-arabic/coffin"},
    
    {w:"coastal", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english-arabic/coastal"},
    {w:"clothing", t:"n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/clothing"},
    {w:"cloning", t:"n", link:"https://dictionary.cambridge.org/dictionary/english/cloning"},
    {w:"clog", t:"v,n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/clog"},
    {w:"cloak", t:"n,v", link:"https://dictionary.cambridge.org/dictionary/english-arabic/cloak"},
    {w:"clique", t:"n", link:"https://dictionary.cambridge.org/dictionary/english/clique"},
    {w:"clinic", t:"n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/clinic"},
    {w:"clingy", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english/clingy"},
    {w:"clench", t:"v", link:"https://dictionary.cambridge.org/dictionary/english/clench"},

    {w:"cleavage", t:"n", link:"https://dictionary.cambridge.org/dictionary/english/cleavage"},
    {w:"clamp", t:"n,v", link:"https://dictionary.cambridge.org/dictionary/english/clamp"},
    {w:"clammy", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english/clammy"},
    {w:"claimant", t:"n", link:"https://dictionary.cambridge.org/dictionary/english/claimant"},
    {w:"civilian", t:"adj,n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/civilian"},
    {w:"cited", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english/cite?q=cited"},
    {w:"chuck", t:"v", link:"https://dictionary.cambridge.org/dictionary/english/chuck"},
    {w:"chronicle", t:"v,n", link:"https://dictionary.cambridge.org/dictionary/english/chronicle"},
    {w:"chronic", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english/chronic"},
    {w:"christian", t:"adj,n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/christian"},

    {w:"chore", t:"n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/chore"},
    {w:"chopped", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english-arabic/chop?q=chopped"},
    {w:"chilling", t:"adj,n", link:"https://dictionary.cambridge.org/dictionary/english/chilling"},
    {w:"chic", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english/chic"},
    {w:"chatty", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english/chatty"},
    {w:"charter", t:"n,v", link:"https://dictionary.cambridge.org/dictionary/english/charter"},
    {w:"allies", t:"n,adj", link:"https://dictionary.cambridge.org/dictionary/english/ally?q=allies"},
    {w:"aboard", t:"adv", link:"https://dictionary.cambridge.org/dictionary/english-arabic/aboard"},
    {w:"assess", t:"v", link:"https://dictionary.cambridge.org/dictionary/english-arabic/assess"},
    {w:"arduous", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english-arabic/arduous"},

    {w:"complementary", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english/complementary"},
    {w:"complexity", t:"n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/complexity"},
    {w:"complimentary", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english-arabic/complimentary"},
    {w:"comprehension", t:"n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/comprehension"},
    {w:"comprise", t:"v", link:"https://dictionary.cambridge.org/dictionary/english-arabic/comprise"},
    {w:"conceited", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english-arabic/conceited"},
    {w:"concept", t:"n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/concept"},
    {w:"concession", t:"n", link:"https://dictionary.cambridge.org/dictionary/english/concession"},
    {w:"concur", t:"v", link:"https://dictionary.cambridge.org/dictionary/english-arabic/concur"},
    {w:"condolence", t:"n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/condolence"},

    {w:"condone", t:"v", link:"https://dictionary.cambridge.org/dictionary/english/condone"},
    {w:"congested", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english/congested"},
    {w:"congestion", t:"n", link:"https://dictionary.cambridge.org/dictionary/english/congestion"},
    {w:"connotation", t:"n", link:"https://dictionary.cambridge.org/dictionary/english/connotation"},
    {w:"conquer", t:"v", link:"https://dictionary.cambridge.org/dictionary/english-arabic/conquer"},
    {w:"conscientious", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english/conscientious"},
    {w:"conserve", t:"v", link:"https://dictionary.cambridge.org/dictionary/english-arabic/conserve"},
    {w:"conserving", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english/conserve?q=conserving"},
    {w:"considerate", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english-arabic/considerate"},
    {w:"consideration", t:"n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/consideration"},


    {w:"constituent", t:"n,adj", link:"https://dictionary.cambridge.org/dictionary/english-arabic/constituent"},
    {w:"constitute", t:"v", link:"https://dictionary.cambridge.org/dictionary/english/constitute"},
    {w:"construct", t:"v,n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/construct"},
    {w:"consumption", t:"n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/consumption"},
    {w:"contaminate", t:"v", link:"https://dictionary.cambridge.org/dictionary/english/contaminate"},
    {w:"contestant", t:"n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/contestant"},
    {w:"context", t:"n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/context"},
    {w:"continuing", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english-arabic/continue?q=continuing"},
    {w:"contractor", t:"n", link:"https://dictionary.cambridge.org/dictionary/english/contractor"},
    {w:"contravene", t:"v", link:"https://dictionary.cambridge.org/dictionary/english/contravene"},


    {w:"contribution", t:"n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/contribution"},
    {w:"controllable", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english/controllable"},
    {w:"controller", t:"n", link:"https://dictionary.cambridge.org/dictionary/english/controller"},
    {w:"converse", t:"adj,v", link:"https://dictionary.cambridge.org/dictionary/english/converse"},
    {w:"convert", t:"v,n", link:"https://dictionary.cambridge.org/dictionary/english/convert"},
    {w:"convoluted", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english/convoluted"},
    {w:"coral", t:"n", link:"https://dictionary.cambridge.org/dictionary/english-arabic/coral"},
    {w:"core", t:"n,v", link:"https://dictionary.cambridge.org/dictionary/english/core"},
    {w:"coronation", t:"n", link:"https://dictionary.cambridge.org/dictionary/english/coronation"},
    {w:"correlation", t:"n", link:"https://dictionary.cambridge.org/dictionary/english/correlation"},

    {w:"corruption", t:"n", link:"https://dictionary.cambridge.org/dictionary/english/corruption"},
    {w:"cot", t:"n,v", link:"https://dictionary.cambridge.org/dictionary/english-arabic/cot"},
    {w:"couch", t:"n,v", link:"https://dictionary.cambridge.org/dictionary/english/couch"},
    {w:"counteract", t:"v", link:"https://dictionary.cambridge.org/dictionary/english/counteract"},
    {w:"counterpart", t:"v", link:"https://dictionary.cambridge.org/dictionary/english/counterpart"},
    {w:"countless", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english/countless"},
    {w:"courageous", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english-arabic/courageous"},
    {w:"courteous", t:"adj", link:"https://dictionary.cambridge.org/dictionary/english-arabic/courteous"},
    {w:"covet", t:"v", link:"https://dictionary.cambridge.org/dictionary/english/covet"},
    {w:"cowboy", t:"n", link:"https://dictionary.cambridge.org/dictionary/english/cowboy"},

    {w:"test", t:"test", link:"test"},
    {w:"test", t:"test", link:"test"},
    {w:"test", t:"test", link:"test"},
    {w:"test", t:"test", link:"test"},
    {w:"test", t:"test", link:"test"},
    {w:"test", t:"test", link:"test"},
    {w:"test", t:"test", link:"test"},
    {w:"test", t:"test", link:"test"},
    {w:"test", t:"test", link:"test"},
    {w:"test", t:"test", link:"test"},

];